# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Quan Qinle
#subtitle: 权芹乐的博客 | QuanQinle's Blog
description: '时间需要留下走过的痕迹'
keywords: 编程, 测试, 计算机, 人生
author: 权芹乐
language:
  - zh-CN
  - en
timezone: 'Asia/Shanghai'

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://quanqinle.github.io
root: /
permalink: :lang/:year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
## File name of new posts
## default-> new_post_name: :title.md
new_post_name: :lang/:year-:month-:day-:title.md
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  # https://github.com/xcatliu/hexo-generator-index-i18n
  ## single_language_index: Show only default language posts at home page. By default is false. 
  ## This means that home page can contain posts written on any language.
  single_language_index: true

# config hexo-generator-i18n option (optional, this is default option)
i18n:
  ## the default of languages is `hexo.config.language`
  # languages: [zh-CN, en]
  type: [page, post]
  generator: [archive, category, tag, index]

# Category & Tag
default_category: uncategorized
## when category is chinese, the url will contain the chinese word, using the following to solve it
category_map:
  编程: programming
  生活: life
  其他: other
tag_map:
  编程: programming
  生活: life
  其他: other

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: date

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
## default -> theme: landscape
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
## Detail: https://hexo.io/zh-cn/docs/one-command-deployment
## 当执行`hexo deploy`时，Hexo会将public目录中的文件和目录推送至如下的远端仓库和分支中，并且完全覆盖该分支下的已有内容。
## 所以，执行该指令可以替代“借助Travis CI部署将Hexo博客部署到GitHub Pages上”的方式。
deploy:
  type: git
  repo: https://github.com/quanqinle/quanqinle.github.io
  branch: master

# Local Search -- add: quanql
## Dependencies: https://github.com/theme-next/hexo-generator-searchdb
search:
  path: search.json
  field: post
  content: true
  format: html
  limit: 100

# hexo-all-minifier
## Dependencies: https://github.com/chenzhutian/hexo-all-minifier
all_minifier: true
js_concator:
  enable: false
  bundle_path: '/js/bundle.js'
  front: false
  silent: false
image_minifier:
  ## fail to deploy, so exclude gif
  enable: false
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false
  silent: false
